name: Certora

on:
  push:
    branches: [master, certora/spec]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
          with:
            node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarnv1-dist-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarnv1-dist-

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc          
          pip3 install certora-cli

      - name: Prepare
        run: |
          chmod +x spec/scripts/*.sh
          ./spec/scripts/applyHarnesses.sh

      - name: Verify with Certora - iTokens
        run: |
          spec/scripts/runRebase.sh
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

  verify_other:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc          
          pip3 install certora-cli

      - name: Build
        run: |
          npm install
          chmod +x spec/scripts/*.sh

      - name: Verify with Certora - Privileged operations Controller
        run: |
          spec/scripts/privilegedController.sh "Controller Privileged operations check"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Verify with Certora - Privileged operations iToken
        run: |
          spec/scripts/privilegediTokens.sh "iToken Privileged operations check"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Verify with Certora - Controller
        run: |
          spec/scripts/controller.sh "Controller CI run"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

      - name: Verify with Certora - reentrancy
        run: |
          spec/scripts/reentrancy.sh "reentrancy guard check CI run"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}    
          
      - name: Verify with Certora - flashloan
        run: |
          spec/scripts/flashloan.sh "flashloan check CI run"
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}    
